# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3eb0f7ba6068af4080f56099ff21da29348aa2e15b8fc2e484b96df07cf15ee0581757c79e203ff3ae45ee7acdb348669cef87c014f90759ea4cff564e82f006

test:
  secret_key_base: ad033eb2db9d4393f858061f1dcd507a256350d56043999d105ad5208aec7412d5efb149738e40ee474aaf9f862b64a4f6a1d30a79b76120b74d94938d9566c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
